name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: chmod 777 ./gradlew && ./gradlew :app:assembleRelease && find app/build/outputs
#    - name: Upload apk
#      uses: actions/upload-artifact@v1
#      with:
#        name: app-armeabi-v7a-release-unsigned.apk
#        path: app/build/outputs/apk/common/release/app-common-armeabi-v7a-release-unsigned.apk

    - name: Upload firmware to cowtransfer
      if: env.UPLOAD_COWTRANSFER == 'true' || contains(github.event.action, 'ssh')
      run: |
        ls -l
        cd app/build/outputs/apk/common/release
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress app-common-armeabi-v7a-release-unsigned.apk 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
    - name: Upload firmware to WeTransfer
      if: env.UPLOAD_WETRANSFER == 'true' || contains(github.event.action, 'ssh')
      run: |
        ls -l
        cd app/build/outputs/apk/common/release
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress app-common-armeabi-v7a-release-unsigned.apk 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
